
#Bucle:
#  diccionario
#    4 veces:
#    maestros
#    dataingesta
#    coordinadores
#      En cada ejecucion mirare si me han pedido 0 replicas... y no hago na....

{{- $tiposNodos := dict "master" .Values.master.deploy "data" .Values.data.deploy "ingest" .Values.ingest.deploy "coordinator" .Values.coordinator.deploy --}}

{{- $ReleaseName := .Release.Name }}
{{- $Elastic := .Values.elastic }}
#{{- with .Values.master.deploy }}

{{ range $tipoNodo, $valores := $tiposNodos }}
{{- $servicio_maestro := include "elasticsearch.nombre-servicio-maestro" $ -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ $ReleaseName }}-master
    labels: 
        app: {{ $ReleaseName }}-es
        tipo-nodo: master
spec:
    replicas: {{ .replicas }}
    selector:
      matchLabels:
        app: {{ $ReleaseName }}-es
        tipo-nodo: master
        
    serviceName: {{ $servicio_maestro }}
    
    template: # Plantilla del POD 
        metadata:
            labels: 
                app: {{ $ReleaseName }}-es
                tipo-nodo: master
        spec:
          {{- with .affinities }}
          affinity: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .tolerations }}
          tolerations: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
      
          {{- with .extraLabels }}
          extraLabels: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          containers:
            - name: elasticSearch
              #image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
              image: {{ include "elasticsearch.imagen-elasticsearch" $ }}
                                                                    # Este $ no nos vale.... y la vamos a tener que liar
              {{- with .resources }}
              resources: 
                {{- toYaml . | nindent 18 }}
              {{- end }}
              ports:
                - containerPort: {{ $Elastic.image.ports.private }}
                - containerPort: {{ $Elastic.image.ports.public }}
              envFrom:
                - configMapRef:
                    name: {{ include "elasticsearch.nombre-configmap-general" $ }}
                - configMapRef: 
                    name: {{ include "elasticsearch.nombre-configmap-default" $ }}
                - configMapRef: 
                    name: {{ $ReleaseName}}-master-es
              env:
                - name: node.name
                  valueFrom: 
                    fieldRef:
                       fieldPath: metadata.name
                - name: node.master
                  value: "true"
                - name: discovery.seed_hosts
                  value: {{ $ReleaseName }}-master-0.{{ $servicio_maestro }},{{ $ReleaseName }}-master-1.{{ $servicio_maestro }}
                - name: ELASTIC_PASSWORD
                  valueFrom:
                        secretKeyRef:
                            name: {{ include "elasticsearch.nombre-secret-general" $ }}
                            key: elastic-user-password
                {{- with .extraEnv }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
              volumeMounts:
                - name: datos-elasticsearch
                  mountPath: /usr/share/elasticsearch/data
                  
    volumeClaimTemplates:
        -   metadata:
                name: datos-elasticsearch
            spec:
                storageClassName: {{ $Elastic.persistence.storageClassName }}
                resources:
                    requests:
                        storage: {{ $Elastic.persistence.capacity }}
                {{- with $Elastic.persistence.accessModes }}
                accessModes: 
                  {{- toYaml . | nindent 18 }}
                {{- end }}
 #{{- end }}
 ---
 {{- end }}
 