
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: {{ .Release.Name}}-deployment-wordpress
spec:
    replicas: {{ .Values.wordpress.deploy.initialReplicaCount }}
    
    selector:
        matchLabels:
            app: {{ .Release.Name }}-wordpress
    
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-wordpress
                {{- with .Values.wordpress.extraLabels }}
                {{- toYaml . | nindent 16 }}
                {{- end }}

        spec:

            {{- with .Values.wordpress.deploy.affinity }}
            affinity: 
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.wordpress.deploy.tolerations }}
            tolerations: 
                {{- toYaml . | nindent 16 }}
            {{- end }}
            volumes:
                - name: datos
                  persistentVolumeClaim:
                    claimName: wordpress-pvc
                
            containers:
                - image: wordpress:php8.0-apache
                  name: wordpress
                  resources:
                    requests:
                        memory: 1024Mi
                        cpu: 1
                    limits:
                        memory: 1024Mi
                        #cpu: ~
                  volumeMounts:
                    - name: datos
                      mountPath: /var/www/html
                  ports:
                    - containerPort: 80
                  env: 
                      - name: WORDPRESS_DB_HOST
                        value: ivanmdb-mariadb
                      - name: WORDPRESS_DB_USER
                        valueFrom: 
                            configMapKeyRef:
                                name: wordpress-configuracion
                                key:  USUARIO
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom: 
                            secretKeyRef:
                                name: mariadb-secretos
                                key:  mariadb-password
                      - name: WORDPRESS_DB_NAME
                        valueFrom: 
                            configMapKeyRef:
                                name: wordpress-configuracion
                                key:  BASE_DE_DATOS
