
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: {{ .Release.Name}}-deployment-wordpress
spec:
    replicas: {{ .Values.wordpress.deploy.initialReplicaCount }}
    
    selector:
        matchLabels:
            app: {{ .Release.Name }}-wordpress
    
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-wordpress
                {{- with .Values.wordpress.extraLabels }}
                {{- toYaml . | nindent 16 }}
                {{- end }}

        spec:

            {{- with .Values.wordpress.deploy.affinity }}
            affinity: 
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.wordpress.deploy.tolerations }}
            tolerations: 
                {{- toYaml . | nindent 16 }}
            {{- end }}
            volumes:
                - name: datos
                {{- if .Values.wordpress.persistence.enabled }}
                  persistentVolumeClaim:
                    claimName: {{ if .Values.wordpress.persistence.existingClaim.enabled }}
                               {{- .Values.wordpress.persistence.existingClaim.name }}
                               {{- else }}
                               {{- .Release.Name }}-pvc-wordpress
                               {{- end }}
                {{- else }}
                  emptyDir: {}  
                {{- end }}
            containers:
                - image:  {{ .Values.wordpress.image.repo }}:{{ .Values.wordpress.image.tag }}
                  name: wordpress
                  {{- with .Values.wordpress.deploy.resources }}
                  resources: 
                      {{- toYaml . | nindent 22 }}
                  {{- end }}
                  volumeMounts:
                    - name: datos
                      mountPath: {{ .Values.wordpress.image.persistentPath }}
                  ports:
                    - containerPort: {{ .Values.wordpress.image.port }}
                  env: 
                      - name: WORDPRESS_DB_HOST
                        value: {{ if .Values.externalDB.enabled -}}
                                {{- .Values.externalDB.host -}}
                                {{- else -}}
                                {{- .Release.Name -}}-mariadb
                                {{- end }}
                      - name: WORDPRESS_DB_USER
                        valueFrom: 
                            configMapKeyRef:
                                name: {{ .Release.Name }}-configmap-wordpress
                                key:  USUARIO
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom: 
                            secretKeyRef:
                            {{- if .Values.externalDB.enabled }}
                                {{- if .Values.externalDB.auth.existingSecret.enabled }}
                                name: {{ .Values.externalDB.auth.existingSecret.name }}
                                key:  {{ .Values.externalDB.auth.existingSecret.key }}
                                {{- else }}
                                name: {{ .Release.Name }}-secret-wordpress
                                key: CONTRASENA
                                {{- end }}
                            {{- else }}
                                {{- if .Values.mariadb.auth.existingSecret }}
                                name: {{ .Values.mariadb.auth.existingSecret }}
                                key:  {{ .Values.mariadb.auth.existingSecret }}
                                {{- else }}
                                name: {{ .Release.Name }}-mariadb
                                key: mariadb-password
                                {{- end }}
                            {{- end }}
                      - name: WORDPRESS_DB_NAME
                        valueFrom: 
                            configMapKeyRef:
                                name: {{ .Release.Name }}-configmap-wordpress
                                key:  BASE_DE_DATOS
