
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
    name: hpa-wordpress
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: mi-wp
    
    minReplicas: 1
    maxReplicas: 5
    
    # Metricas
    targetCPUUtilizationPercentage: 50