{{ with .Values.wordpress.deploy.autoscale }}
{{ if and (.enabled) (or (.cpu) (.memory)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
    name:  {{ $.Release.Name }}-hpa-wordpress
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ $.Release.Name }}-deployment-wordpress
    
    minReplicas: {{ .min }}
    maxReplicas: {{ .max }}
    
    # Metricas
    #targetCPUUtilizationPercentage: 50
    metrics:
    {{- if .cpu }}
        - type: Resource
          resource:
            name: cpu
            type: Utilization
            averageUtilization: {{ .cpu }}
    {{- end }}            
    {{- if .memory }}
        - type: Resource
          resource:
            name: memory
            type: Utilization
            averageUtilization: {{ .memory }}
        {{ end }}            
    {{ end }}            
{{ end }}            
            