{{ if or (and (.Values.externalDB.enabled) (not .Values.externalDB.auth.existingSecret.enabled)) 
         (and (.Values.mariadb.enabled)    (not .Values.mariadb.auth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata: 
    name: {{ .Release.Name }}-secret-wordpress
data:
    CONTRASENA: {{ if .Values.externalDB.enabled -}}
                {{- .Values.externalDB.auth.password | b64enc -}}
                {{- else -}}
                {{- .Values.mariadb.auth.password | b64enc -}}
                {{- end }}
{{ end }}