
apiVersion: v1
kind: Service
metadata: 
    name: {{ if .Values.wordpress.service.nameOverride.fullOverride -}}
            {{- .Values.wordpress.service.nameOverride.fullOverride -}}
            {{- else -}}
            {{- .Release.Name }}-{{ .Values.wordpress.service.nameOverride.suffixOverride | default "wordpress" -}}
            {{- end }}
spec:
    type: {{ .Values.wordpress.service.type }}
    ports:
        - port: {{ .Values.wordpress.service.port }}
          targetPort: {{ .Values.wordpress.image.port }}
          {{- if and (eq .Values.wordpress.service.type "NodePort") (.Values.wordpress.service.nodePort) }}
          nodePort: {{ .Values.wordpress.service.nodePort }}
          {{- end }}
          {{- if and (eq .Values.wordpress.service.type "LoadBalancer") (.Values.wordpress.service.loadBalancerIP) }}
          loadBalancerIP: {{ .Values.wordpress.service.loadBalancerIP }}
          {{- end }}
    selector:
        app: {{ .Release.Name }}-wordpress