---
# Source: wordpress/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata: 
    name: RELEASE-NAME-configmap-wordpress
data:
    USUARIO: 
    BASE_DE_DATOS:
---
# Source: wordpress/templates/service.yaml
apiVersion: v1
kind: Service
metadata: 
    name: RELEASE-NAME-wordpress
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: RELEASE-NAME-wordpress
---
# Source: wordpress/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: RELEASE-NAME-deployment-wordpress
spec:
    replicas: 58
    
    selector:
        matchLabels:
            app: RELEASE-NAME-wordpress
    
    template:
        metadata:
            labels:
                app: RELEASE-NAME-wordpress

        spec:
            volumes:
                - name: datos
                  persistentVolumeClaim:
                    claimName: RELEASE-NAME-pvc-wordpress
            containers:
                - image:  MIREPO:MI-TAG
                  name: wordpress
                  resources:
                      limits:
                        cpu: 2
                      requests:
                        memory: 10Gi
                  volumeMounts:
                    - name: datos
                      mountPath: /var/www/html
                  ports:
                    - containerPort: 80
                  env: 
                      - name: WORDPRESS_DB_HOST
                        value: ivanmdb-mariadb
                      - name: WORDPRESS_DB_USER
                        valueFrom: 
                            configMapKeyRef:
                                name: wordpress-configuracion
                                key:  USUARIO
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom: 
                            secretKeyRef:
                                name: mariadb-secretos
                                key:  mariadb-password
                      - name: WORDPRESS_DB_NAME
                        valueFrom: 
                            configMapKeyRef:
                                name: wordpress-configuracion
                                key:  BASE_DE_DATOS
---
# Source: wordpress/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
    name:  RELEASE-NAME-hpa-wordpress
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: RELEASE-NAME-deployment-wordpress
    
    minReplicas: 1
    maxReplicas: 10
    
    # Metricas
    #targetCPUUtilizationPercentage: 50
    metrics:
        - type: Resource
          resource:
            name: cpu
            type: Utilization
            averageUtilization: 2
        - type: Resource
          resource:
            name: memory
            type: Utilization
            averageUtilization: 2000Mi
