kind: Service
apiVersion: v1
metadata:
    name: {{ include "elasticsearch.nombre-servicio-ingesta" $ }}
spec:
    type: {{ .Values.ingest.service.type }}
    selector:
        app: {{ .Release.Name }}-es
        tipo-nodo: ingest
    ports:
        - name: externo
          port: {{ .Values.ingest.service.ports.public }}
          targetPort: {{ .Values.elastic.image.ports.public }}
        - name: interno
          port: {{ .Values.ingest.service.ports.private }}
          targetPort: {{ .Values.elastic.image.ports.private }}